"""add checked_at to qc_report

Revision ID: 6631be89ec8c
Revises: d9566cb7c2c0
Create Date: 2025-08-20 11:04:29.156287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6631be89ec8c'
down_revision: Union[str, None] = 'd9566cb7c2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qc_report', sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_qc_report_checked_at'), 'qc_report', ['checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_report_checked_at'), table_name='qc_report')
    op.drop_column('qc_report', 'checked_at')
    # ### end Alembic commands ###
