"""change fields for invoice_payment models

Revision ID: 67bce026d5b6
Revises: 79041cdb9bc5
Create Date: 2025-08-27 10:48:46.245360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67bce026d5b6'
down_revision: Union[str, None] = '79041cdb9bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_line', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoice_line', 'qty',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               nullable=True)
    op.alter_column('invoice_line', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('invoice_line', 'line_total',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.add_column('payment', sa.Column('note', sa.Text(), nullable=True))
    op.drop_constraint('payment_invoice_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'vendor_invoice', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vendor_invoice', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_invoice', 'issued_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_invoice_id_fkey', 'payment', 'vendor_invoice', ['invoice_id'], ['id'])
    op.drop_column('payment', 'note')
    op.alter_column('invoice_line', 'line_total',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('invoice_line', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('invoice_line', 'qty',
               existing_type=sa.NUMERIC(precision=18, scale=3),
               nullable=False)
    op.alter_column('invoice_line', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
