"""change created_at for model purhchase_return

Revision ID: 79041cdb9bc5
Revises: 6631be89ec8c
Create Date: 2025-08-27 10:26:34.442056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79041cdb9bc5'
down_revision: Union[str, None] = '6631be89ec8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_return', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('return_line', 'reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_line', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('purchase_return', 'created_at')
    # ### end Alembic commands ###
