"""add type accpeted_by for models QCLine

Revision ID: e3d24f52a0d4
Revises: 760239ef3b35
Create Date: 2025-08-19 20:03:57.558721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d24f52a0d4'
down_revision: Union[str, None] = '760239ef3b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qc_line', sa.Column('accepted_qty', sa.Numeric(precision=18, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qc_line', 'accepted_qty')
    # ### end Alembic commands ###
